Rideshare.Web/Areas/Admin/Models/Subforums/SubforumFormViewModel.cs
namespace Rideshare.Web.Areas.Admin.Models.Subforums
{
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class SubforumFormViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public int SelectedCategory { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }

        public int CurrentCategoryId { get; set; }
    }
}

Rideshare.Web/Areas/Admin/Controllers/SubforumsController.cs
namespace Rideshare.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Rideshare.Service.Contracts.Admin.Forum;
    using Rideshare.Service.Models.Forum.Categories;
    using Rideshare.Web.Areas.Admin.Models.Subforums;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class SubforumsController : BaseController
    {
        private readonly ICategoryService categories;
        private readonly ISubforumService subforums;

        public SubforumsController(ICategoryService categories, ISubforumService subforums)
        {
            this.categories = categories;
            this.subforums = subforums;
        }

        public async Task<IActionResult> Index()
            => View(await this.subforums.AllAsync());

        public async Task<IActionResult> Create(int? categoryId)
        {
            var categories = await this.categories.AllAsync();
            var categoriesList = SetCategoriesList(categories);

            var model = new SubforumFormViewModel { Categories = categoriesList };

            if (categoryId != null)
            {
                model.CurrentCategoryId = (int)categoryId;
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SubforumFormViewModel model)
        {
            await this.subforums.CreateAsync(model.Name, model.SelectedCategory);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var subforum = await this.subforums.ByIdAsync(id);

            if (subforum == null)
            {
                return BadRequest();
            }

            var categories = await this.categories.AllAsync();
            var categoriesList = SetCategoriesList(categories);

            var model = new SubforumFormViewModel
            {
                Id = id,
                Name = subforum.Name,
                Categories = categoriesList,
                CurrentCategoryId = subforum.CategoryId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SubforumFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = SetCategoriesList(await this.categories.AllAsync());
                return View(model);
            }

            await this.subforums.EditAsync(model.Id, model.Name, model.SelectedCategory);
            return RedirectToAction(nameof(Index));
        }

        private static IEnumerable<SelectListItem> SetCategoriesList(IEnumerable<CategoryListingModel> categories)
        {
            return categories.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString(),
            });
        }
    }
}

Rideshare.Web/Areas/Admin/Views/Subforums/Create.cshtml
@model SubforumFormViewModel

@{
    ViewData["Title"] = "Create new subforum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-3">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categories"></label>
                <select name="SelectedCategory" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        if (category.Value.ToString() == Model.CurrentCategoryId.ToString())
                        {
                            <option value="@category.Value.ToString()" selected>@category.Text</option>
                        }
                        else
                        {
                            <option value="@category.Value.ToString()">@category.Text</option>
                        }
                    }
                </select>
                <span asp-validation-for="Categories" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success col-md-4">Create</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Rideshare.Web/Areas/Admin/Views/Subforums/Edit.cshtml
@model SubforumFormViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-3">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categories"></label>
                <select name="SelectedCategory" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        if (category.Value.ToString() == Model.CurrentCategoryId.ToString())
                        {
                            <option value="@category.Value.ToString()" selected>@category.Text</option>
                        }
                        else
                        {
                            <option value="@category.Value.ToString()">@category.Text</option>
                        }
                    }
                </select>
                <span asp-validation-for="Categories" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success col-md-4">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Rideshare.Web/Areas/Admin/Views/Subforums/Index.cshtml
@model IEnumerable<CategorySubforumsModel>

    @{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h1 class="text-center" style="margin-bottom:50px;">Subforums</h1>

    @foreach (var category in Model)
    {
    <form asp-action="Create" method="get">
        <h5 class="text-center">
            Category: @category.Name
            <input type="submit" class="btn btn-success float-right" value="Create"/>
            <input type="hidden" name="categoryId" value="@category.Id" />
        </h5>
    </form>
    <hr />
    <div class="row">
        @foreach (var subforum in category.Subforums)
        {
        <div class="col-md-3">
            <div class="card" style="margin-bottom:20px;">
                <div class="card-body text-center">
                    <h4 class="card-title">@subforum.Name</h4>
                    <p class="card-text text-muted">@subforum.Topics.Count topics <br /> @subforum.Topics.Sum(t => t.RepliesCount) replies</p>
                    <a asp-controller="Subforums" asp-action="Edit" asp-route-id="@subforum.Id" class="btn btn-warning btn-block">Edit</a>
                </div>
            </div>
        </div>
        }
    </div>
    }