Rideshare.Web/Controllers/CarsController.cs
namespace Rideshare.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Model;
    using Rideshare.Service.Contracts;
    using Rideshare.Service.Models.Cars;
    using System.Threading.Tasks;

    [Authorize]
    public class CarsController : Controller
    {
        private readonly ICarService cars;
        private readonly IPhotoService photos;
        private readonly UserManager<User> userManager;

        public CarsController(ICarService cars, IPhotoService photos, UserManager<User> userManager)
        {
            this.cars = cars;
            this.photos = photos;
            this.userManager = userManager;
        }

        public IActionResult Create()
            => View(new CarFormModel());

        [HttpPost]
        public async Task<IActionResult> Create(CarFormModel carModel)
        {
            if (!ModelState.IsValid)
            {
                return View(carModel);
            }

            var userId = this.userManager.GetUserId(User);

            byte[] photo = await this.photos.ConvertToBytesAsync(carModel.Photo);

            await this.cars.CreateAsync(carModel.Make, carModel.Model, carModel.Color, carModel.Year, photo,
                carModel.HasRoomForLuggage, carModel.HasAirConditioner, carModel.IsSmokingAllowed, 
                carModel.IsFoodAllowed, carModel.AreDrinksAllowed, carModel.ArePetsAllowed, userId);

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var ownerId = this.userManager.GetUserId(User);
            var car = await this.cars.ByIdAsync(id, ownerId);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CarFormModel carModel)
        {
            if (!ModelState.IsValid)
            {
                return View(carModel);
            }

            var ownerId = this.userManager.GetUserId(User);

            byte[] photo = await this.photos.ConvertToBytesAsync(carModel.Photo);

            var success = await this.cars.EditAsync(id, carModel.Make, carModel.Model, carModel.Color,
                carModel.Year, photo, carModel.HasRoomForLuggage, carModel.HasAirConditioner, carModel.IsSmokingAllowed, 
                carModel.IsFoodAllowed, carModel.AreDrinksAllowed, carModel.ArePetsAllowed, ownerId);

            if (!success)
            {
                return BadRequest();
            }

            TempData["Success"] = "Changes were saved successfully.";
            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var ownerId = this.userManager.GetUserId(User);

            if (!await this.cars.BelongsToUser(id, ownerId))
            {
                return BadRequest();
            }

            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCar(int id)
        {
            var ownerId = this.userManager.GetUserId(User);

            var success = await this.cars.DeleteAsync(id, ownerId);

            if (!success)
            {
                return BadRequest();
            }

            TempData["Success"] = "Your car was deleted successfully.";
            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> All()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.cars.AllAsync(userId));
        }
    }
}

Rideshare.Web/Controllers/MessagesController.cs
namespace Rideshare.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Model;
    using Rideshare.Service.Contracts;
    using Rideshare.Service.Models.Messages;
    using System;
    using System.Threading.Tasks;

    [Authorize]
    public class MessagesController : Controller
    {
        private readonly IMessageService messages;
        private readonly UserManager<User> userManager;

        public MessagesController(IMessageService messages, UserManager<User> userManager)
        {
            this.messages = messages;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Received()
        {
            string userId = GetCurrentUserId();
            var messages = await this.messages.ReceivedAsync(userId);

            return View(messages);
        }

        public async Task<IActionResult> Sent()
        {
            string userId = GetCurrentUserId();
            var messages = await this.messages.SentAsync(userId);

            return View(messages);
        }

        public IActionResult Send(string recipient)
        {
            if (recipient == null)
            {
                return View(new MessageFormModel());
            }
            else
            {
                return View(new MessageFormModel { Recipient = recipient });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Send(MessageFormModel model)
        {
            var senderId = GetCurrentUserId();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var recipient = await this.userManager.FindByNameAsync(model.Recipient);

            if (recipient == null)
            {
                TempData["Error"] = "There is no such user. Please try again!";
                return View(model);
            }

            await this.messages.SendAsync(model.Title, model.Content, senderId, recipient.Id, DateTime.UtcNow);

            return RedirectToAction(nameof(Sent));
        }

        public async Task<IActionResult> Details(string id)
        {
            var message = await this.messages.DetailsByIdAsync(id);
            var currentUserId = GetCurrentUserId();

            if (message.SenderId != currentUserId && message.RecipientId != currentUserId)
            {
                return BadRequest();
            }

            if (message.RecipientId == GetCurrentUserId())
            {
                await this.messages.MarkAsReadAsync(id);
            }

            return View(message);
        }

        public async Task<IActionResult> MarkAsUnread(string id)
        {
            await this.messages.MarkAsUnreadAsync(id);

            return RedirectToAction(nameof(Received));
        }

        private string GetCurrentUserId()
            => this.userManager.GetUserId(User);
    }
}

Rideshare.Web/Controllers/TravelsController.cs
namespace Rideshare.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Rideshare.Model;
    using Rideshare.Service.Contracts;
    using Rideshare.Service.Models.Users;
    using Rideshare.Web.Models.Reviews;
    using Rideshare.Web.Models.Travels;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class TravelsController : Controller
    {
        private readonly ITravelService travels;
        private readonly ICarService cars;
        private readonly IReviewService reviews;
        private readonly UserManager<User> userManager;

        public TravelsController(ITravelService travels, ICarService cars, IReviewService reviews,
            UserManager<User> userManager)
        {
            this.travels = travels;
            this.cars = cars;
            this.reviews = reviews;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
            => View(await this.travels.ActiveAsync());

        public async Task<IActionResult> Search(string start, string destination)
            => View(await this.travels.SearchAsync(start, destination));

        public async Task<IActionResult> Details(int id)
        {
            var userId = this.userManager.GetUserId(User);

            if (!await this.travels.ExistsAsync(id))
            {
                return NotFound();
            }

            return View(await this.travels.DetailsAsync(id, userId));
        }

        [Authorize]
        public async Task<IActionResult> Apply(int id)
        {
            var userId = this.userManager.GetUserId(User);

            await this.travels.ApplyAsync(id, userId);

            return RedirectToAction(nameof(Details), new { id });
        }

        [Authorize]
        public async Task<IActionResult> Cancel(int id)
        {
            var userId = this.userManager.GetUserId(User);

            await this.travels.CancelApplicationAsync(id, userId);

            return RedirectToAction(nameof(Details), new { id });
        }

        public async Task<IActionResult> Accept(int id, string userId)
        {
            await this.travels.AcceptAsync(id, userId);

            return RedirectToAction(nameof(Details), new { id });
        }

        public async Task<IActionResult> Reject(int id, string userId)
        {
            await this.travels.RejectAsync(id, userId);

            return RedirectToAction(nameof(Details), new { id });
        }

        public async Task<IActionResult> Rate(int id)
        {
            var userId = this.userManager.GetUserId(User);
            var travel = await this.travels.ByIdAsync(id);

            if (travel == null)
            {
                return NotFound();
            }

            var driverId = travel.DriverId;
            var passengers = travel.Passengers;

            var userIsDriver = driverId == userId;
            var userIsPassenger = passengers.Any(p => p.Id == userId);

            List<SelectListItem> ratings = SetRatingsList();
            var travelHasFinished = travel.TravelTime < DateTime.UtcNow.ToLocalTime();

            if (userIsDriver)
            {
                List<SelectListItem> passengersList = await SetPassengersList(userId, passengers);

                return View("RatePassengers", new ReviewFormViewModel
                {
                    TravelId = id,
                    Passengers = passengersList,
                    Ratings = ratings,
                    TravelHasFinished = travelHasFinished
                });
            }
            else if (userIsPassenger)
            {
                //Driver can only get 1 review from the same passenger (regardless of number of trips together)
                var hasMatch = await this.reviews.ContainsUsers(driverId, userId);

                return View("RateDriver", new ReviewFormViewModel
                {
                    TravelId = id,
                    DriverId = driverId,
                    Ratings = ratings,
                    TravelHasFinished = travelHasFinished,
                    ReviewIsAllowed = !hasMatch
                });
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Rate(ReviewFormViewModel model, string id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var authorId = this.userManager.GetUserId(User);
            var userId = model.SelectedPassenger == null ? id : model.SelectedPassenger;

            await this.reviews.CreateAsync(userId, model.SelectedRating, model.Comment, authorId);

            var user = await this.userManager.FindByIdAsync(userId);
            TempData["Success"] = $"{user.Name} was succcessfully rated.";

            return RedirectToAction(nameof(Rate), new { id = model.TravelId });
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            List<SelectListItem> cars = await SetCarsList();

            return View(new TravelFormViewModel
            {
                TravelTime = DateTime.UtcNow.Date.AddDays(1),
                Cars = cars
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(TravelFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Cars = await this.SetCarsList();
                return View(model);
            }

            var driverId = this.userManager.GetUserId(User);

            await this.travels.CreateAsync(model.StartingPoint, model.Destination, model.TravelTime, model.Price,
                model.AvailableSeats, model.AdditionalInfo, driverId, model.SelectedCar);

            return RedirectToAction(nameof(UsersController.UpcomingTravels), "Users");
        }

        private async Task<List<SelectListItem>> SetCarsList()
        {
            var userId = this.userManager.GetUserId(User);
            var availableCars = await this.cars.AllAsync(userId);

            var cars = availableCars
                .Select(c => new SelectListItem
                {
                    Text = c.Make + " " + c.Model,
                    Value = c.Id.ToString()
                })
                .ToList();

            return cars;
        }

        private async Task<List<SelectListItem>> SetPassengersList(string driverId, List<UserProfileModel> passengers)
        {
            var passengersList = new List<SelectListItem>();

            foreach (var passenger in passengers)
            {
                //Passenger can only get 1 review from the same driver (regardless of number of trips together)
                var hasMatch = await this.reviews.ContainsUsers(passenger.Id, driverId);

                if (!hasMatch)
                {
                    passengersList.Add(new SelectListItem
                    {
                        Text = passenger.Name,
                        Value = passenger.Id.ToString()
                    });
                }
            }

            return passengersList;
        }

        private static List<SelectListItem> SetRatingsList()
        {
            var grades = new List<int> { 1, 2, 3, 4, 5 };

            var ratings = grades
                .Select(r => new SelectListItem
                {
                    Text = r.ToString(),
                    Value = r.ToString()
                })
                .ToList();

            return ratings;
        }
    }
}

Rideshare.Web/Controllers/UsersController.cs
namespace Rideshare.Web.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Model;
    using Rideshare.Service.Contracts;
    using System.Threading.Tasks;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly UserManager<User> userManager;

        public UsersController(IUserService users, UserManager<User> userManager)
        {
            this.users = users;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Profile(string username)
        {
            if (username == null)
            {
                return NotFound();
            }

            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            var profile = await this.users.ProfileAsync(user.Id);
            profile.TimesAsADriver = this.users.TimesAsADriver(user.Id);

            return View(profile);
        }

        [Route("[controller]/travels/upcoming")]
        public async Task<IActionResult> UpcomingTravels()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.users.UpcomingTravelsAsync(userId));
        }

        [Route("[controller]/travels/history")]
        public async Task<IActionResult> TravelHistory()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.users.TravelHistoryAsync(userId));
        }
    }
}

Rideshare.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rideshare</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<body style="background-color:aliceblue;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rideshare</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown show">
                            <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Travels
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <a class="dropdown-item" asp-controller="Travels" asp-action="Create">Create</a>
                                }
                                <a class="dropdown-item" asp-controller="Travels" asp-action="Index">Active</a>
                            </div>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="All">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Profile" asp-route-username="@User.Identity.Name">Profile</a>
                            </li>
                            <li class="nav-item dropdown show">
                                <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    My travels
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="/Users/Travels/Upcoming">Upcoming</a>
                                    <a class="dropdown-item" href="/Users/Travels/History">History</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-area="" asp-controller="Messages" asp-action="Received"><i class="far fa-envelope"></i> PMs</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Forum" asp-controller="Home" asp-action="Index">Forum</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown show">
                                <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Categories">Categories</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Subforums">Subforums</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @if (TempData.ContainsKey("Success"))
            {
                <div class="alert alert-success">
                    @TempData["Success"]
                </div>
            }
            else if (TempData.ContainsKey("Error"))
            {
                <div class="alert alert-danger">
                    @TempData["Error"]
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2019 - Rideshare @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>