Rideshare.Web/Areas/Forum/Controllers/HomeController.cs
namespace Rideshare.Web.Areas.Forum.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Service.Contracts.Forum;
    using System.Threading.Tasks;

    public class HomeController : BaseController
    {
        private readonly IForumService forum;

        public HomeController(IForumService forum)
        {
            this.forum = forum;
        }

        public async Task<IActionResult> Index()
            => View(await this.forum.ShowAsync());
    }
}

Rideshare.Web/Areas/Forum/Controllers/TopicsController.cs
namespace Rideshare.Web.Areas.Forum.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Model;
    using Rideshare.Service.Contracts.Admin.Forum;
    using Rideshare.Service.Contracts.Forum;
    using Rideshare.Web.Areas.Forum.Models.Replies;
    using Rideshare.Web.Areas.Forum.Models.Topics;
    using System.Threading.Tasks;

    public class TopicsController : BaseController
    {
        private readonly IHtmlService html;
        private readonly ITopicService topics;
        private readonly ISubforumService subforums;
        private readonly UserManager<User> userManager;

        public TopicsController(IHtmlService html, ITopicService topics, ISubforumService subforums, UserManager<User> userManager)
        {
            this.html = html;
            this.topics = topics;
            this.subforums = subforums;
            this.userManager = userManager;
        }

        public async Task<IActionResult> All(int subforumId)
        {
            if (!await SubforumExists(subforumId))
            {
                return NotFound();
            }

            var topics = new TopicListingViewModel
            {
                SubforumId = subforumId,
                Topics = await this.topics.BySubforumAsync(subforumId)
            };

            return View(topics);
        }

        public async Task<IActionResult> Show(int id)
        {
            var topic = await this.topics.ByIdAsync(id);

            if (topic == null)
            {
                return BadRequest();
            }

            return View(topic);
        }

        [Authorize]
        public async Task<IActionResult> Create(int subforumId)
        {
            if (!await SubforumExists(subforumId))
            {
                return NotFound();
            }

            return View(new TopicFormViewModel { SubforumId = subforumId });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(TopicFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!await SubforumExists(model.SubforumId))
            {
                return BadRequest();
            }

            model.Content = this.html.Sanitize(model.Content);
            var authorId = this.userManager.GetUserId(User);

            await this.topics.CreateAsync(model.Name, model.Content, authorId, model.SubforumId);

            return RedirectToAction(nameof(All), new { subforumId = model.SubforumId });
        }

        [Authorize]
        public async Task<IActionResult> Reply(int topicId)
        {
            if (!await TopicExists(topicId))
            {
                return NotFound();
            }

            return View(new ReplyFormViewModel { TopicId = topicId });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Reply(ReplyFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!await TopicExists(model.TopicId))
            {
                return BadRequest();
            }

            model.Content = this.html.Sanitize(model.Content);
            var authorId = this.userManager.GetUserId(User);
            await this.topics.ReplyAsync(model.Content, authorId, model.TopicId);

            return RedirectToAction(nameof(Show), new { id = model.TopicId });
        }

        private async Task<bool> SubforumExists(int subforumId)
            => await this.subforums.Exists(subforumId);

        private async Task<bool> TopicExists(int topicId)
            => await this.topics.Exists(topicId);
    }
}

Rideshare.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Rideshare.Web.Models;

namespace Rideshare.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rideshare.Web/Areas/Forum/Views/Home/Index.cshtml
@model IEnumerable<CategorySubforumsModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var row = 1;
    string trClass;
}

<h1>Forum</h1><br />

<div class="row">
    <div class="col-md-10 text-center">
        @foreach (var category in Model)
        {
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th colspan="4" class="table-active">@category.Name <i class="fa fa-minus-circle" id="hide" aria-hidden="true"></i></th>
                    </tr>
                    <tr>
                        <th></th>
                        <th>Subforum</th>
                        <th>Statistics</th>
                        <th>Last post</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var subforum in category.Subforums)
                    {
                        var lastSubforumActivity = subforum.Topics.OrderByDescending(t => t.LastReplyPublished).FirstOrDefault();

                        if (row % 2 == 0)
                        {
                            trClass = "";
                        }
                        else
                        {
                            trClass = "table-info";
                        }

                        <tr class="@trClass">
                            <th scope="row"><i class="fa fa-comments fa-lg" aria-hidden="true"></i></th>
                            <td><a asp-controller="Topics" asp-action="All" asp-route-subforumId="@subforum.Id"><strong>@subforum.Name</strong></a>
                            <td class="small">@subforum.Topics.Count topics <br />@subforum.Topics.Sum(t => t.RepliesCount) replies</td>
                            <td class="small">
                                @if (lastSubforumActivity != null)
                                {
                                    <a asp-controller="Topics" asp-action="Show" asp-route-id="@lastSubforumActivity.Id">@lastSubforumActivity.Name</a>
                                    <br /> <span>@lastSubforumActivity.LastReplyAuthor » @lastSubforumActivity.LastReplyPublished.ToString("dd.M.yyyy г. HH:mm ч.")</span>
                                }
                            </td>
                        </tr>

                        row++;
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<script src="~/js/hideForumCategories.js" type="text/javascript"></script>
<script>hide();</script>