Rideshare.Web/Controllers/MessagesController.cs
namespace Rideshare.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Model;
    using Rideshare.Service.Contracts;
    using Rideshare.Service.Models.Messages;
    using System;
    using System.Threading.Tasks;

    [Authorize]
    public class MessagesController : Controller
    {
        private readonly IMessageService messages;
        private readonly UserManager<User> userManager;

        public MessagesController(IMessageService messages, UserManager<User> userManager)
        {
            this.messages = messages;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Received()
        {
            string userId = GetCurrentUserId();
            var messages = await this.messages.ReceivedAsync(userId);

            return View(messages);
        }

        public async Task<IActionResult> Sent()
        {
            string userId = GetCurrentUserId();
            var messages = await this.messages.SentAsync(userId);

            return View(messages);
        }

        public IActionResult Send(string recipient)
        {
            if (recipient == null)
            {
                return View(new MessageFormModel());
            }
            else
            {
                return View(new MessageFormModel { Recipient = recipient });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Send(MessageFormModel model)
        {
            var senderId = GetCurrentUserId();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var recipient = await this.userManager.FindByNameAsync(model.Recipient);

            if (recipient == null)
            {
                TempData["Error"] = "There is no such user. Please try again!";
                return View(model);
            }

            await this.messages.SendAsync(model.Title, model.Content, senderId, recipient.Id, DateTime.UtcNow);

            return RedirectToAction(nameof(Sent));
        }

        public async Task<IActionResult> Details(string id)
        {
            var message = await this.messages.DetailsByIdAsync(id);
            var currentUserId = GetCurrentUserId();

            if (message.SenderId != currentUserId && message.RecipientId != currentUserId)
            {
                return BadRequest();
            }

            if (message.RecipientId == GetCurrentUserId())
            {
                await this.messages.MarkAsReadAsync(id);
            }

            return View(message);
        }

        public async Task<IActionResult> MarkAsUnread(string id)
        {
            await this.messages.MarkAsUnreadAsync(id);

            return RedirectToAction(nameof(Received));
        }

        private string GetCurrentUserId()
            => this.userManager.GetUserId(User);
    }
}

Rideshare.Web/Controllers/UsersController.cs
namespace Rideshare.Web.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Rideshare.Model;
    using Rideshare.Service.Contracts;
    using System.Threading.Tasks;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly UserManager<User> userManager;

        public UsersController(IUserService users, UserManager<User> userManager)
        {
            this.users = users;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Profile(string username)
        {
            if (username == null)
            {
                return NotFound();
            }

            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            var profile = await this.users.ProfileAsync(user.Id);
            profile.TimesAsADriver = this.users.TimesAsADriver(user.Id);

            return View(profile);
        }

        [Route("[controller]/travels/upcoming")]
        public async Task<IActionResult> UpcomingTravels()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.users.UpcomingTravelsAsync(userId));
        }

        [Route("[controller]/travels/history")]
        public async Task<IActionResult> TravelHistory()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.users.TravelHistoryAsync(userId));
        }
    }
}

Rideshare.Web/Views/Messages/Details.cshtml
@inject UserManager<User> userManager
@model MessageDetailsModel

@{
    ViewData["Title"] = "Message details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var profilePictureSrc = (Model.SenderProfilePicture != null) ?
    @Model.SenderProfilePicture : "/images/noImage.png";

    var currentUserId = userManager.GetUserId(User);
}

<h1>@ViewData["Title"]</h1><br />

<div class="row">
    <div class="col-md-2 text-center">
        <img src="@profilePictureSrc" class="rounded-circle" style="height:12vw;" /><br />
        <a asp-controller="Users" asp-action="Profile" asp-route-username="@Model.Sender">@Model.Sender</a>
    </div>
    <div class="col-md-8">
        <div class="card bg-light">
            <div class="card-body">
                <p>
                    <b>@Model.Title</b><br />
                    <b>Sent: </b>@Model.DateTime<br />
                    <b>From: </b><a asp-controller="Users" asp-action="Profile" asp-route-username="@Model.Sender">@Model.Sender</a><br />
                    <b>To: </b><a asp-controller="Users" asp-action="Profile" asp-route-username="@Model.Recipient">@Model.Recipient</a>
                </p>
                <hr />
                <p>@Model.Content</p>
            </div>
        </div><br />
        @if (currentUserId == Model.RecipientId)
        {
            <form asp-controller="Messages" asp-action="Send" method="get">
                <input type="submit" class="btn btn-success btn-block col-md-2" value="Reply" />
                <input type="hidden" name="recipient" value="@Model.Sender" />
            </form>
        }
    </div>
</div>

Rideshare.Web/Views/Messages/Received.cshtml
@model IEnumerable<MessageListingModel>

@{
    ViewData["Title"] = "Received";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Messages</h1>
<hr /><br />

<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item"><a class="nav-link" asp-action="Send">Send new message</a></li>
            <li class="nav-item"><a class="nav-link active" asp-action="Received">Received</a></li>
            <li class="nav-item"><a class="nav-link" asp-action="Sent">Sent</a></li>
        </ul>
    </div>

    <div class="col-md-9">
        @if (!Model.Any())
        {
            <h3>Your message box is empty!</h3>
        }
        else
        {
            foreach (var message in Model)
            {
                <p>
                    @if (message.IsRead)
                    {
                        <i class="fa fa-envelope-open fa-lg" aria-hidden="true"></i>
                        <a asp-controller="Messages" asp-action="Details" asp-route-id="@message.Id">@message.Title</a><br />
                        <span>From: <a asp-controller="Users" asp-action="Profile" asp-route-username="@message.Sender">@message.Sender</a> » @message.DateTime</span><br />
                        <a asp-controller="Messages" asp-action="MarkAsUnread" asp-route-id="@message.Id" class="text-danger">Mark as unread</a>
                    }
                    else
                    {
                        <i class="fa fa-envelope fa-lg text-danger" aria-hidden="true"></i>
                        <a asp-controller="Messages" asp-action="Details" asp-route-id="@message.Id">@message.Title</a><br />
                        <span>From: <a asp-controller="Users" asp-action="Profile" asp-route-username="@message.Sender">@message.Sender</a> » @message.DateTime</span><br />
                    }
                </p>
                <hr />
            }
        }
    </div>
</div>

Rideshare.Web/Views/Messages/Send.cshtml
@model MessageFormModel

@{
    ViewData["Title"] = "Send Message";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <h2>@ViewData["Title"]</h2>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Recipient"></label>
        <input asp-for="Recipient" class="form-control" />
        <span asp-validation-for="Recipient" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" rows="5" class="form-control"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success col-md-4">Send</button>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Rideshare.Web/Views/Messages/Sent.cshtml
@model IEnumerable<MessageListingModel>

@{
    ViewData["Title"] = "Sent Messages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Messages</h1>
<hr /><br />

<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item"><a class="nav-link" asp-action="Send">Send new message</a></li>
            <li class="nav-item"><a class="nav-link" asp-action="Received">Received</a></li>
            <li class="nav-item"><a class="nav-link active" asp-action="Sent">Sent</a></li>
        </ul>
    </div>

    <div class="col-md-9">
        @if (!Model.Any())
        {
            <h4>Your have not sent any messages!</h4>
        }
        else
        {
            foreach (var message in Model)
            {
                <p>
                    <i class="far fa-envelope fa-lg"></i>
                    <a asp-controller="Messages" asp-action="Details" asp-route-id="@message.Id">@message.Title</a><br />
                    To: <a asp-controller="Users" asp-action="Profile" asp-route-username="@message.Recipient">@message.Recipient</a> » @message.DateTime
                    <hr>
                </p>
            }
        }
    </div>
</div>